todo_list/mytodos/urls.py
from django.urls import path 

from mytodos import views



urlpatterns = [

    path('mytodos/home/', views.HomeView.as_view(), name='home'),

    path('mytodos/add/', views.TaskAddView.as_view(), name='task-add'),

    path('mytodos/<int:pk>/change/', views.TaskEditView.as_view(), name='task-edit'),

    path('mytodos/<int:pk>/remove/', views.TaskDeleteView.as_view(), name='task-delete'),

    path('mytodos/register/', views.SignUpView.as_view(), name='register'),

    path('', views.SignInView.as_view(), name='signin'),

    path('mytodos/signout/', views.SignOutView.as_view(), name='signout'),

]

todo_list/todo_list/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('mytodos.urls')),
]

todo_list/mytodos/models.py
from django.db import models

from django.contrib.auth.models import User

# Create your models here.

class Task(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)

    title = models.CharField(max_length=300)

    description = models.TextField(null=True, blank=True)

    completed = models.BooleanField(default=False)

    date_created = models.DateTimeField(auto_now_add=True)


    class Meta:

        ordering = ['completed']


    def __str__(self):

        return self.title
    

    

todo_list/mytodos/forms.py
from django import forms 

from mytodos.models import Task

from django.contrib.auth.models import User

from django.contrib.auth.forms import UserCreationForm

from django.contrib.auth import password_validation

class TaskForm(forms.ModelForm):

    class Meta:

        model = Task

        #fields = '__all__'

        exclude = ('user','date_created')

        widgets = {
            
            'title': forms.TextInput(attrs={'class': 'form-control mb-3'}),

            'description': forms.Textarea(attrs={'class': 'form-control mb-3', 'rows':4}),

            'completed': forms.CheckboxInput(attrs={'class': 'form-check'}),

        }


class RegisterForm(UserCreationForm):

    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}), label="Password", 
                                help_text=password_validation.password_validators_help_text_html(),)
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}), label='Confirm password')

    class Meta:

        model = User

        fields = ['username', 'email', 'password1', 'password2']

        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control mb-3'}),
            'email': forms.EmailInput(attrs={'class': 'form-control mb-3'}),
            

        }


class LoginForm(forms.Form):

    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))

    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))

todo_list/mytodos/views.py
from django.shortcuts import render, redirect

from django.views.generic import View

from mytodos.models import Task

from mytodos.forms import TaskForm, RegisterForm, LoginForm

from django.contrib.auth.models import User

from django.contrib.auth import authenticate, login, logout

from django.utils import timezone

from django.db.models import Count

from django.contrib import messages

from mytodos.decorators import signin_required

from django.utils.decorators import method_decorator

from django.views.decorators.cache import never_cache



# Create your views here.

decorator_list = [signin_required, never_cache]


@method_decorator(decorator_list, name='dispatch')
class HomeView(View):

    def get(self, request, *args, **kwargs):

        qs = Task.objects.filter(user=request.user)

        completed_tasks = qs.filter(completed=True)

        pending_tasks = qs.filter(completed=False)

        completed_count = completed_tasks.aggregate(total_count=Count("id"))

        pending_count = pending_tasks.aggregate(total_count=Count("id"))

        # print(completed_count)
        # print(pending_count)

        group_by_count = Task.objects.filter(user=request.user).values('completed').annotate(total=Count("id"))
        # print(group_by_count)

        all_count = Task.objects.filter(user=request.user).values('completed').aggregate(total=Count("id"))
        # print(all_count)

        form = TaskForm()

        return render(request, 'home.html', {
                                                'data':qs, 
                                                'completed_tasks': completed_tasks, 
                                                'pending_tasks': pending_tasks,
                                                'completed_count': completed_count,
                                                'pending_count': pending_count,
                                                'all_count': all_count,
                                                'form': form,
                                                })
    

    def post(self, request, *args, **kwargs):

        form = TaskForm(request.POST)

        if form.is_valid():

            form.instance.user = request.user

            form.save()

            messages.success(request, 'Task added.')
            
            return redirect('home')
        
        


@method_decorator(decorator_list, name='dispatch')    
class TaskAddView(View):

    def get(self, request, *args, **kwargs):

        form = TaskForm()

        return render(request, 'task_add.html', {'form': form})
    
    def post(self, request, *args, **kwargs):

        form = TaskForm(request.POST)

        if form.is_valid():

            form.instance.user = request.user

            form.save()

            messages.success(request, 'Task Added')

            return redirect('home')
        
        messages.error(request, 'ERROR ! Task failed to add.')
    
        return render(request, 'task_add.html', {'form': form})
    



@method_decorator(decorator_list, name='dispatch')
class TaskEditView(View):
    
    def get(self, request, *args, **kwargs):

        task_object = Task.objects.get(id=kwargs.get('pk'))

        form = TaskForm(instance=task_object)

        return render(request, 'task_edit.html', {'form': form})
    
    def post(self, request, *args, **kwargs):

        task_object = Task.objects.get(id=kwargs.get('pk'))

        form = TaskForm(request.POST, instance=task_object)

        if form.is_valid():

            form.save()

            messages.success(request, 'Task edited.')

            return redirect('home')
        
        messages.error(request, 'ERROR ! Task not updated.')

        return render(request, 'task_edit.html', {'form': form})
    
        

@method_decorator(decorator_list, name='dispatch')    
class TaskDeleteView(View):

    def get(self, request, *args, **kwargs):

        Task.objects.get(id=kwargs.get('pk')).delete();

        messages.success(request, 'Task deleted.')

        return redirect('home')
    


# url: localhost:8000/register/
# method: get, post

class SignUpView(View):

    def get(self, request, *args, **kwargs):

        form = RegisterForm()

        return render(request, 'register.html', {'form': form})
    
    def post(self, request, *args, **kwargs):

        form = RegisterForm(request.POST)

        if form.is_valid():

            #User.objects.create_user(**form.cleaned_data)

            form.save()

            messages.success(request, 'User account created.')

            return redirect('signin')
        
        messages.error(request, 'ERROR ! Account not created, try again.')
        
        return render(request, 'register.html', {'form': form})
    



class SignInView(View):

    def get(self, request, *args, **kwargs):

        form = LoginForm()

        return render(request, 'login.html', {'form': form})
    
    def post(self, request, *args, **kwargs):

        form = LoginForm(request.POST)

        if form.is_valid():

            data = form.cleaned_data

            uname = data.get('username')

            pwd = data.get('password')

            user_object = authenticate(request, username=uname, password=pwd)

            if user_object:

                login(request, user_object)
                
                messages.success(request, 'Logged In')

                return redirect('home')
            
        messages.error(request, 'ERROR ! Login failed.')
        
        return render(request, 'login.html', {'form': form})
    



@method_decorator(decorator_list, name='dispatch')
class SignOutView(View):

    def get(self, request, *args, **kwargs):

        logout(request)

        messages.success(request, 'Logged Out')

        return redirect('signin')
    

todo_list/mytodos/templates/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign In</title>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
        integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

</head>

<style>
    @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;900&display=swap');

    body {
        font-family: 'Popins', sans-serif;
        /*background-color: rgba(52, 52, 116, 0.701);*/
        background-color: #8EC5FC;
        background-image: linear-gradient(62deg, #8EC5FC 0%, #E0C3FC 100%);
        background-attachment: fixed;
    }

    form p:nth-of-type(2) {
        position: relative;
    }

    form p i {
        position: absolute;
        bottom: 9px; right: 9px;
        cursor: pointer;
    }

    .login-div {
        min-width: 300px;
    }

</style>

<body class="">


    <div class="container">
        <div class="row">
            <div class="col-md-2 col-lg-3"></div>
            <div class="col-md-8 col-lg-6">
                <div class="login-div shadow border border-2 rounded p-3 p-md-5 mt-5 bg-light">

                    <h2 class="text-center mb-3 mt-2 p-2 text-primary-emphasis lh-2"><span class="border rounded-5 px-3 py-2 bg-secondary-subtle">My Todo List</span></h2>
                    <h3 class="text-center mb-3 text-primary-emphasis">Sign In</h3>

                    <div>
                    {% if messages %}
                        
                        {% for m in messages %}
                            
                            {% if m.level == DEFAULT_MESSAGE_LEVELS.ERROR  %}
                                <div class="alert alert-danger alert-dismissible fade show text-center alert-message" role="alert">
                                    <strong>{{ m }}</strong>
                                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                                </div>
                            
                            {% else %}

                            <div class="alert alert-success alert-dismissible fade show text-center alert-message" role="alert">
                                <strong>{{ m }}</strong>
                                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                            </div>

                            {% endif %}
                        
                        {% endfor %}
            
                    {% endif %}

                    </div>
                    


                    <form action="" method="post" class="">

                        {% csrf_token %}

                        {{form.as_p}}

                        <div class="text-center mt-4">
                            <button type="submit" class="btn btn-primary px-4 btn">Login</button>
                            
                        </div>

                    </form>
                    <div class="mt-4 text-center">
                        <a href="{% url 'register' %}" class="text-success">Don't have an account? <span class="text-danger fw-bolder">Register</span></a>
                    </div>
                </div>
            </div>
            <div class="col-md-2 col-lg-3"></div>
        </div>
    </div>


</body>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

<script>

    // message timer 

    if (document.querySelector('.alert-message')) {
        setTimeout(function(){
            document.querySelector('.alert-message button').click();
        },2000)
    }


    // password show and hide

    document.querySelector('form p:nth-of-type(2)').insertAdjacentHTML('afterbegin', '<i class="fa-solid fa-eye" title="Show"></i>')
    
   
    document.querySelector('form p i').addEventListener('click', function() {
        if (this.classList.contains('fa-eye')) {
            this.classList.replace('fa-eye', 'fa-eye-slash');
            document.querySelector('#id_password').setAttribute('type', 'text')
            this.setAttribute('title', 'Hide')
        } else {
            this.classList.replace('fa-eye-slash', 'fa-eye');
            document.querySelector('#id_password').setAttribute('type', 'password')
            this.setAttribute('title', 'Show')
            
        }
    })
  

</script>

</html>

todo_list/mytodos/templates/register.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Register</title>

    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
      integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />

    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
      crossorigin="anonymous"
    />
  </head>

  <style>
    @import url("https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;900&display=swap");

    body {
      font-family: "Popins", sans-serif;
      /*background-color: rgba(52, 52, 116, 0.701);*/

      background-color: #8EC5FC;
      background-image: linear-gradient(62deg, #8EC5FC 0%, #E0C3FC 100%);

      background-attachment: fixed;
    }

    form p:nth-of-type(3),
    form p:nth-of-type(5) {
      position: relative;
    }

    form p i {
      position: absolute;
      bottom: 9px;
      right: 9px;
      cursor: pointer;
    }

    .register-div {
      min-width: 300px;
    }
    

    .errorlist{
        list-style: none;
        color: red;
    }
   
  </style>

  <body class="">
    <div class="container">
      <div class="row">
        <div class="col-md-2 col-lg-3"></div>
        <div class="col-md-8 col-lg-6">
          <div class="register-div shadow border border-2 rounded p-3 p-md-5 mt-5 bg-light my-4">

            <h2 class="text-center mb-3 mt-2 p-2 text-primary-emphasis lh-2"><span class="border rounded-5 px-3 py-2 bg-secondary-subtle">My Todo List</span></h2>
            <h3 class="text-center mb-3 text-primary-emphasis">Sign Up</h3>

            {% if messages %}
            
              {% for m in messages %}
                  
                  {% if m.level == DEFAULT_MESSAGE_LEVELS.ERROR  %}
                      <div class="alert alert-danger alert-dismissible fade show alert-message" role="alert">
                          <strong>{{ m }}</strong>
                          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                      </div>
                  
                  {% else %}

                    <div class="alert alert-success alert-dismissible fade show alert-message" role="alert">
                        <strong>{{ m }}</strong>
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>

                  {% endif %}
              
              {% endfor %}
            
            {% endif %}




            <form action="" method="post" >
              {% csrf_token %} 
              
              {{form.as_p}}

              <div class="text-center mt-4">
                <button type="submit" class="btn btn-primary px-4 btn">
                  Create account
                </button>

              </div>
            </form>
            <div class="mt-4 text-center">
              <a href="{% url 'signin' %}" class="text-success">Already have an account? <span class="text-danger fw-bolder">Login</span></a>
            </div>
          </div>
        </div>
        <div class="col-md-2 col-lg-3"></div>
      </div>
    </div>

   
   
   
   
   
   
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
      crossorigin="anonymous"></script>


    <script>


      // message timer 

      if (document.querySelector('.alert-message')) {
        setTimeout(function(){
            document.querySelector('.alert-message button').click();
        },2000)
      }


      // password show and hide

        document.querySelector("form p:nth-of-type(3)").insertAdjacentHTML("afterbegin", '<i class="fa-solid fa-eye" title="Show"></i>');
        document.querySelector("form p:nth-of-type(5)").insertAdjacentHTML("afterbegin", '<i class="fa-solid fa-eye" title="Show"></i>');

        document.querySelectorAll("form p i").forEach(function (elem, index) {
            elem.addEventListener("click", function () {

                if (this.classList.contains("fa-eye")) {

                    this.classList.replace("fa-eye", "fa-eye-slash");
                    
                    document.querySelector(`#id_password${index + 1}`).setAttribute("type", "text");

                    this.setAttribute('title', 'Hide')
           
                } else {

                    this.classList.replace("fa-eye-slash", "fa-eye");
                    document.querySelector(`#id_password${index + 1}`).setAttribute("type", "password");
                    this.setAttribute('title', 'Show')
            
                }
        });
      });


    </script>
    
  </body>
</html>

todo_list/mytodos/templates/task_add.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Task Add</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

</head>

<style>
    @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;900&display=swap');

    body {
        font-family: 'Popins', sans-serif;
        /*background-color: rgba(52, 52, 116, 0.701);*/

        background-color: #8EC5FC;
        background-image: linear-gradient(62deg, #8EC5FC 0%, #E0C3FC 100%);

        background-attachment: fixed;
    }

    .add-task {
        min-width: 300px;
    }
    
</style>

<body class="">

    
    <div class="container">
        <div class="row">
            <div class="col-md-2 col-lg-3"></div>
            <div class="col-md-8 col-lg-6"> 
                <div class="add-task shadow rounded p-3 mt-5 bg-light">
                    <h2 class="text-center mb-3 mt-2 p-2 text-primary-emphasis lh-2"><span class="border rounded-5 px-3 py-2 bg-secondary-subtle">My Todo List</span></h2>
                    <h3 class="text-center mb-3 text-primary-emphasis">Add Task</h3>

                    {% if messages %}
            
                        {% for m in messages %}

                            <div class="alert alert-danger alert-dismissible fade show text-center" role="alert">
                                <strong>{{ m }}</strong>
                                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                            </div>
                        
                        {% endfor %}
            
                    {% endif %}

                    <form action="" method="post" class="">
    
                        {% csrf_token %}

                        <label for="id_title">Title</label>
                        {{form.title}}
                        <label for="id_description">Description</label>
                        {{form.description}}
                        
    
                        <div class="text-center">
                            <button type="submit" class="btn btn-primary px-4 btn-sm">Add</button>
                            <a href="{% url 'home' %}"  class="btn btn-secondary btn-sm">Cancel</a>
                        </div>
    
                    </form>

                </div>
            </div>
            <div class="col-md-2 col-lg-3"></div>
        </div>
    </div>

    

</body>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

</html>

todo_list/mytodos/templates/task_edit.html
<!DOCTYPE html>

{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Task Edit</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">


</head>

<style>
    @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;900&display=swap');

    body {
        font-family: 'Popins', sans-serif;
        /*background-color: rgba(52, 52, 116, 0.701);*/

        background-color: #8EC5FC;
        background-image: linear-gradient(62deg, #8EC5FC 0%, #E0C3FC 100%);

        background-attachment: fixed;
    }


    div:has(>input[type='checkbox']) {
        display: inline-flex;
        margin-bottom: 10px;
    }

    input[type='checkbox'] {
        margin-inline: 7px;
        width: 16px;
        color: green;
        
    }
    input[type='checkbox']:focus {
        background-color: white;
        color: green;
    }

    /*
    input[type='checkbox']:checked {
        background-color: white;
        color: green;
    }
    */

    form div:has(input[type='checkbox']) {
        
        position: relative;
        
    }

    input[type='checkbox']::after {
        content: '✔';
        font-size: 35px;
        border-radius: 50px;
        background-color: rgba(248, 249, 250, 0.718);
        width: 30px;
        height: 30px;
        text-align: center;
        position: absolute;
        top: -4px;
        left: 84px;
        line-height: 22px;
        display: var(--display-item, none);
    }

    input[type='checkbox'].active::after{
        display: var(--display-item, block);
    }
    
</style>

<body class="edit-task">
    
    <div class="container">
        <div class="row">
            <div class="col-md-2 col-lg-3"></div>
            <div class="col-md-8 col-lg-6">
                <div class="shadow rounded p-3 mt-5 bg-light" style="min-width: 300px;">
                    <h2 class="text-center mb-3 mt-2 p-2 text-primary-emphasis lh-2"><span class="border rounded-5 px-3 py-2 bg-secondary-subtle">My Todo List</span></h2>
                    <h3 class="text-center mb-3 text-primary-emphasis">Edit Task</h3>

                    {% if messages %}
            
                        {% for m in messages %}

                            <div class="alert alert-danger alert-dismissible fade show text-center" role="alert">
                                <strong>{{ m }}</strong>
                                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                            </div>
                        
                        {% endfor %}
            
                    {% endif %}



                    <form action="" method="post" class="">
    
                        {% csrf_token %}

                        {{form}}
                    
                        <div class="text-center">
                            <button type="submit" class="btn btn-primary btn-sm">Save Changes</button>
                            <a href="{% url 'home' %}"  class="btn btn-secondary btn-sm">Cancel</a>
                        </div>
    
                    </form>

                </div>
            </div>
            <div class="col-md-2 col-lg-3"></div>
        </div>
    </div>



</body>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>


<script>

// tick mark

if(document.querySelector('input[type="checkbox"]').checked) {
    document.querySelector('input[type="checkbox"]').classList.add('active')

}

document.querySelector('input[type="checkbox"]').addEventListener('click', function(e){
    this.classList.toggle('active')
})



</script>

</html>